tests: Move tests into @group Database
LogicException: This test does not need DB but tried to access it anyway

Follow-Up: Iabca65ae545400ecb893e5c1b506cc289da58b03
Change-Id: I263ea2cbd495c1d924b9b6c18f06f5c1bed12178