Add missing \ to Title
Fatal error:  Class 'MediaWiki\Extensions\OAuth\Title' not found in
OAuth/frontend/specialpages/SpecialMWOAuth.php on line 210

Change-Id: I929d8afd326dbf4467be3bd276b19f2758292fb1